### ISSUE TITLE
Actividad 10 corregida: Tengo dudas (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [emasmas0407/Unidad-3-Programaci-n#10]
El código está bien, demasiado bien. Realizas cosas adicionales que están genial, pero que no se piden, como comprobar que la nota sea válida. Además utilizas instrucciones que no hemos estudiado, como `push`. 

Tengo dudas sobre si la actividad la has hecho tú o la ha hecho otra persona (o inteligencia artificial). Necesito hablar contigo para comprobar si el código ha sido escrito por ti. Por ahora dejo la actividad sin calificar.

**Comment by emasmas0407** [comment]
Lo he hecho yo, pero en esta ultima actividad que es la 10 le he pedido ayuda a otra persona porque no lo entendía muy bien y el día que explicaste esta actividad falte a clases, entonces por eso le he pedido ayuda a otra persona.

**Comment by cborcar637** [comment]
Bueno, pues vamos a hacer una cosa. Realiza las modificaciones oportunas para que quede como se pide. En otras palabras, no se debe tener en cuenta si la nota es válida, es decir, se aceptará 12 como nota.

Para ello, borra la línea `let nota;`, borra la estructura `if` completa y, finalmente, borra la línea `notas.push(nota)` que hay debajo de la estructura `if`.

Tras ello, el código no te funcionará, porque a la línea `notas = parseInt(prompt("¿Qué nota le pones a " + alumnos[i] + "?"));` le falta algo que deberás de averiguar y solucionar por ti sola. Averígualo y te la califico bien.

**Comment by emasmas0407** [comment]
Vale.

**Comment by emasmas0407** [comment]
Corregido.

**Comment by cborcar637** [comment]
Ok, ya está bien. Cierro la solicitud. Por cierto, tienes todas las solicitudes abiertas, cierra las que estén bien.
