### ISSUE TITLE
Actividad 3 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [emasmas0407/Unidad-3-Programaci-n#3]
La función que se invoca desde el botón la has llamado `hola()` y debería llamarse `pedirDatos()`, tal y como se indica en la descripción de la actividad en el PDF.

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by emasmas0407** [comment]
Corregido.

**Comment by cborcar637** [comment]
Has cambiado el nombre de la función en el HTML, pero en el código JavaScript sigue llamándose `hola()`, por lo que la actividad no funciona.

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado.

**Comment by emasmas0407** [comment]
Corregido.

**Comment by cborcar637** [comment]
Revisado, ya funciona correctamente. Cierro la solicitud
