### ISSUE TITLE
Actividad 8 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [emasmas0407/Unidad-3-Programaci-n#8]
El mensajeSwitch() se muestra con alert y debe mostrarse con document.getElement....

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by emasmas0407** [comment]
Corregido.

**Comment by cborcar637** [comment]
Revisado. Está bien
